### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Hugo-Contreras** [ciena-frost/ember-frost-ecosystem#11]
Trying to install the ember-frost-ecosystem in a new Ember application generated with the `ember new` command, I select the packages I want to install and the ones I want to keep and then when I launch the installation I've got an error an the installation stop.

```
Installing packages for tooling via npmmodule.js:471
    throw err;
    ^

Error: Cannot find module './dir-reader.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

Configuration :
- MacOS 10.11.6
- Node.js 6.10.1
- NPM 3.10.10
- Ember CLI 2.8.0

**Comment by dafortin** [comment]
What is the selected list of packages?

**Comment by dafortin** [comment]
I did try to reproduce the issues:
```
ember new my-app
npm install && bower install 
ember install ember-frost-ecosystem
```

The selected packages installed sucessfully.
